<?php
/**
 * Issue
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
/**
 * Issue tracking service
 *
 * Issue tracking service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */
/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;


/**
 * Class representing the Issue model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Issue
{

    /**
     * identifier of the issue
     *
     * @var int
     * @SerializedName("id")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;
    /**
     * identifier of the project
     *
     * @var int
     * @SerializedName("project_id")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $projectId;
    /**
     * type of the issue
     *
     * @var string
     * @SerializedName("type")
     * @Assert\NotNull()
     * @Assert\Choice({ "topic", "config", "action", "design", "dev" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;
    /**
     * title of the issue
     *
     * @var string
     * @SerializedName("title")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $title;
    /**
     * time spent on this issue
     *
     * @var float
     * @SerializedName("time")
     * @Assert\NotNull()
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $time;
    /**
     * time spent on this issue and its childs
     *
     * @var float
     * @SerializedName("total_time")
     * @Assert\NotNull()
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $totalTime;
    /**
     * child issues with the same schema
     *
     * @var OpenAPI\Server\Model\Issue[]|null
     * @SerializedName("childs")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Issue")
     * })
     * @Type("array<OpenAPI\Server\Model\Issue>")
     */
    protected $childs;

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->projectId = isset($data['projectId']) ? $data['projectId'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->title = isset($data['title']) ? $data['title'] : null;
        $this->time = isset($data['time']) ? $data['time'] : null;
        $this->totalTime = isset($data['totalTime']) ? $data['totalTime'] : null;
        $this->childs = isset($data['childs']) ? $data['childs'] : null;
    }

    /**
     * Gets id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int $id identifier of the issue
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets projectId.
     *
     * @return int
     */
    public function getProjectId()
    {
        return $this->projectId;
    }

    /**
     * Sets projectId.
     *
     * @param int $projectId identifier of the project
     *
     * @return $this
     */
    public function setProjectId($projectId)
    {
        $this->projectId = $projectId;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string $type type of the issue
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Sets title.
     *
     * @param string $title title of the issue
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Gets time.
     *
     * @return float
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Sets time.
     *
     * @param float $time time spent on this issue
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->time = $time;

        return $this;
    }

    /**
     * Gets totalTime.
     *
     * @return float
     */
    public function getTotalTime()
    {
        return $this->totalTime;
    }

    /**
     * Sets totalTime.
     *
     * @param float $totalTime time spent on this issue and its childs
     *
     * @return $this
     */
    public function setTotalTime($totalTime)
    {
        $this->totalTime = $totalTime;

        return $this;
    }

    /**
     * Gets childs.
     *
     * @return OpenAPI\Server\Model\Issue[]|null
     */
    public function getChilds(): ?array
    {
        return $this->childs;
    }

    /**
     * Sets childs.
     *
     * @param OpenAPI\Server\Model\Issue[]|null $childs child issues with the same schema
     *
     * @return $this
     */
    public function setChilds(array $childs = null)
    {
        $this->childs = $childs;

        return $this;
    }
}


