<?php
/**
 * ProjectsApiInterface
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Issue tracking service
 *
 * Issue tracking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\CreateProject;
use OpenAPI\Server\Model\Project;
use OpenAPI\Server\Model\ProjectCreated;
use OpenAPI\Server\Model\ProjectName;

/**
 * ProjectsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ProjectsApiInterface
{

    /**
     * Operation projectProjectIdGet
     *
     * Find project by ID
     *
     * @param  int $projectId  ID of the project to display (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Project
     *
     */
    public function projectProjectIdGet($projectId, &$responseCode, array &$responseHeaders);

    /**
     * Operation projectProjectIdPut
     *
     * Update project by ID
     *
     * @param  int $projectId  ID of the project to update (required)
     * @param  OpenAPI\Server\Model\ProjectName $projectName  Name (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function projectProjectIdPut($projectId, ProjectName $projectName, &$responseCode, array &$responseHeaders);

    /**
     * Operation projectsGet
     *
     * Lists projects
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\Project[]
     *
     */
    public function projectsGet(&$responseCode, array &$responseHeaders);

    /**
     * Operation projectsPost
     *
     * Add a new project to the tracker
     *
     * @param  OpenAPI\Server\Model\CreateProject $createProject  Project object (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\ProjectCreated
     *
     */
    public function projectsPost(CreateProject $createProject, &$responseCode, array &$responseHeaders);
}
